language: php

php:
  - 5.6

env:
  - MONGO_DRIVER=mongo

matrix:
  include:
    - php: 5.6
      env: MONGO_DRIVER=mongo COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.0
      env: ADAPTER_VERSION="^1.0.0" MONGO_DRIVER=mongodb

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_install:
  - yes '' | pecl -q install -f $MONGO_DRIVER
  - if [ "x${ADAPTER_VERSION}" != "x" ]; then composer require "alcaeus/mongo-php-adapter=${ADAPTER_VERSION}" --ignore-platform-reqs; fi

install:
  - composer update $COMPOSER_FLAGS

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
