language: php
sudo: false

php:
  - 7.2

env:
  global:
    - DRIVER_VERSION="stable"
    - COMPOSER_FLAGS="--prefer-dist"

matrix:
  include:
    - php: 7.2
      env: DRIVER_VERSION="stable" COMPOSER_FLAGS="--prefer-dist"
    - php: 7.2
      env: DRIVER_VERSION="1.5.0" COMPOSER_FLAGS="--prefer-dist --prefer-lowest" PHPUNIT_FLAGS="--coverage-clover=coverage.clover"

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

install:
  - composer self-update
  - pecl install -f mongodb-${DRIVER_VERSION}
  - composer update ${COMPOSER_FLAGS}

script:
    - ./vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
